baseURL = 'https://sabot.unv.app/'
title = 'Save Any Bot'
disablePathToLower = true
enableGitInfo = true
defaultContentLanguage = 'zh'


[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookTheme = 'auto'
BookToC = true
BookLogo = 'logo.png'
BookSection = '*'
BookRepo = 'https://github.com/krau/saveany-bot'
BookCommitPath = 'commit'
BookEditPath = 'edit/main/docs'
BookDateFormat = '2006/01/02'
BookSearch = false

[languages]

[languages.zh]
languageName = "简体中文"
contentDir = "content/zh"
weight = 1

[[languages.zh.menu.before]]
name = "🔗 GitHub"
url = "https://github.com/krau/SaveAny-Bot"
weight = 10

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 2

[[languages.en.menu.before]]
name = "🔗 GitHub"
url = "https://github.com/krau/SaveAny-Bot"
weight = 10

[markup]
[markup.goldmark.renderer]
unsafe = true
